Package ‘pivottabler’
February 17, 2019
Type Package
Title Create Pivot Tables in R
Version 1.1.0

#### Description
 Create regular pivot tables with just a few lines of R.
More complex pivot tables can also be created, e.g. pivot tables with irregular layouts, multiple calculations and/or derived
calculations based on multiple data frames. Pivot tables are onstructed using R only and can be written to a range of
output formats (plain text, 'HTML', 'Latex' and 'Excel'), including with styling/formatting.
Depends R (>= 3.3.0)
Imports R6 (>= 2.2.0), dplyr (>= 0.5.0), data.table (>= 1.10.0), jsonlite (>= 1.1), htmltools(>= 0.3.5), htmlwidgets (>= 0.8)
Suggests ggplot2 (>= 2.2.0), lubridate (>= 1.5.0), listviewer (>= 1.4.0), openxlsx (>= 4.0.17), basictabler (>= 0.2.0), shiny,
knitr, rmarkdown, testthat
License GPL-3
Encoding UTF-8
LazyData true
URL https://github.com/cbailiss/pivottabler
BugReports https://github.com/cbailiss/pivottabler/issues
VignetteBuilder knitr
RoxygenNote 6.1.1
NeedsCompilation no
Author Christopher Bailiss [aut, cre]
Maintainer Christopher Bailiss <cbailiss@gmail.com>
Repository CRAN
Date/Publication 2019-02-17 13:50:03 UTC


41bhmtraindisruption
PivotStyles . . . .
PivotTable . . . . .
pivottabler . . . . .
pivottablerOutput .
processIdentifier . .
processIdentifiers .
pvtperfresults . . .
pvtperfsummary . .
qhpvt . . . . . . .
qlpvt . . . . . . . .
qpvt . . . . . . . .
renderBasicTable .
renderPivottabler .
skipExportingValue
trainstations . . . 

Index
bhmtraindisruption


