PivotOpenXlsxStyles
PivotOpenXlsxStyles
A class that defines a collection of Excel styles as used by the openxlsx
package.

#### Description

The PivotOpenXlsxStyles class stores a collection of PivotTableOpenXlsx style objects.

#### Usage
<pre><code>

PivotOpenXlsxStyles
Format
R6Class object.
Value
Object of R6Class with properties and methods that define styles/a theme for a pivot table.
Fields
parentPivot Owning pivot table.
Methods
Documentation For more complete explanations and examples please see the extensive vignettes
supplied with this package.
new(...) Create a new set of styles, specifying the field values documented above.
findNamedStyle(baseStyleName) Find an existing openxlsx style matching the name of a base
style.
findOrAddStyle(action="findOrAdd", baseStyleName=NULL, isBaseStyle=NULL, style=NULL, mapFromCss=TRUE
Find an existing openxlsx style and/or add a new openxlsx style matching a base style and/or
PivotStyle object.
addNamedStyles(mapFromCss=TRUE) Populate the OpenXlsx styles based on the styles defined in
the pivot table.
asList() Get a list representation of the styles.
asJSON() Get a JSON representation of the styles.
asString() Get a text representation of the styles.

#### Examples
```{r}

# This class is used internally by the Pivot Table.PivotStyle
```
