PivotData
A class that contains named data frames.

#### Description

The PivotData class stores all of the data frames associated with a pivot table.

#### Usage
<pre><code>

PivotData
Format
R6Class object.
Value
Object of R6Class with properties and methods that help quickly storing and retrieving data frames.
Fields
parentPivot Owning pivot table.
Methods
Documentation For more complete explanations and examples please see the extensive vignettes
supplied with this package.
new(...) Create a new pivot data container, specifying the field value documented above.
addData(df, dataName) And a data frame to the pivot table, specifying a name that can be used
to easily retrieve it or refer to it later.
getData(dataName) Get the data frame with the specified name.
isKnownData(dataName)) Check if a data frame exists with the specified name.
asList() Get a list representation of the contained data frames.
asJSON() Get a JSON representation of the contained data frames.

#### Examples
```{r}

# This class should only be created by the pivot table.
# It is not intended to be created outside of the pivot table.PivotDataGroup
```
