PivotCalculationGroup
PivotCalculationGroup A class that defines a group of calculations.

#### Description

The PivotCalculationGroup class is a container for multiple PivotCalculation objects.

#### Usage
<pre><code>

PivotCalculationGroup
Format
R6Class object.
Value
Object of R6Class with properties and methods that define a group of calculations.
Fields
parentPivot Owning pivot table.
calculationGroupName Calculation group unique name. Recommendation: Do not have spaces
in this name.
Methods
Documentation For more complete explanations and examples please see the extensive vignettes
supplied with this package.
new(...) Create a new pivot calculation group, specifying the field values documented above.
isExistingCalculation(calculationName=NULL) Check if a calculation exists with the speci-
fied name in this calculation group.
getCalculation(calculationName=NULL) Get the calculation with the specified name.
defineCalculation(calculationName=NULL, caption=NULL, visible=TRUE, displayOrder=NULL, filters=NULL,
Create a new calculation. See the PivotCalculation class documentation for more details
on the arguments.
asList() Get a list representation of this calculation group.
asJSON() Get a JSON representation of this calculation group.
asString() Get a text representation of this calculation group.

#### Examples
```{r}

# This class should only be created by the pivot table.
# It is not intended to be created outside of the pivot table.PivotCalculationGroups
23
```
