
qpvt
Quickly build a basic pivot table.

#### Description

The qpvt function builds a basic pivot table with one line of R.qpvt
53

#### Usage
<pre><code>

qpvt(dataFrame, rows = NULL, columns = NULL, calculations = NULL,
theme = NULL, replaceExistingStyles = FALSE, tableStyle = NULL,
headingStyle = NULL, cellStyle = NULL, totalStyle = NULL, ...)

</code></pre>
#### Arguments

dataFrame The data frame containing the data to be summarised in the pivot table.
rows A character vector of variable names to be plotted on the rows of the pivot table,
or "=" to specify the position of the calculations.
columns A character vector of variable names to be plotted on the columns of the pivot
table, or "=" to specify the position of the calculations.
calculations One or more summary calculations to use to calculate the values of the cells in
the pivot table.
theme Either the name of a built-in theme (default, largeplain, compact or blank/none)
or a list which specifies the default formatting for the table.
replaceExistingStyles
TRUE to completely replace the default styling with the specified tableStyle,
headingStyle, cellStyle and/or totalStyle
tableStyle A list of CSS style declarations that apply to the table.
headingStyle A list of CSS style declarations that apply to the heading cells in the table.
cellStyle A list of CSS style declarations that apply to the normal cells in the table.
totalStyle A list of CSS style declarations that apply to the total cells in the table.
... Additional arguments, currently format, formats, totals, compatibility and/or ar-
gumentCheckMode.
Value
A pivot table.

#### Examples
```{r}

qpvt(bhmtrains, "TOC", "TrainCategory", "n()")
qpvt(bhmtrains, c("=", "TOC"), c("TrainCategory", "PowerType"),
c("Number of Trains"="n()",
"Maximum Speed"="max(SchedSpeedMPH, na.rm=TRUE)"))54
renderPivottabler
