Character Functions in R
========================================================


## Character Manipulation
R is usually thought of as a language designed for numerical computation,
it contains a full complement of functions which can manipulate character
data.

<p>
*  The \texttt{nchar()} function can be used to find the number of characters in a character value.
*  Character values will be displayed when they are passed to the  \texttt{print()} function.
*  The \texttt{cat()}  function will combine
character values and print them to the screen or a file directly. The \texttt{cat()}
function coerces its arguments to character values, then concatenates and displays
them. This makes the function ideal for printing messages and warnings
from inside of functions.
<p>

## Regular Expressions in <tt>R</tt>
Regular expressions are a method of expressing patterns in character values
which can then be used to extract parts of strings or to modify those strings in some way. Regular expressions are supported in the <tt>R</tt> functions \texttt{strsplit()},
\texttt{grep()}, \texttt{sub()}, and \texttt{gsub()}, as well as in the\texttt{ regexp()} and \texttt{gregexpr()} functions which
are the main tools for working with regular expressions in <tt>R</tt>.


%-----------------------------------------------------------%
\subsection{Breaking Apart Character Values}

The \texttt{strsplit()} function can use a character string or regular expression to divide
up a character string into smaller pieces. The first argument to\texttt{strsplit()} 
is the character string to break up, and the second argument is the character
value or regular expression which should be used to break up the string into
parts.
%-----------------------------------------------------------%



### Letters functtion

### Case functions
 - toupper(x)	Uppercase
 - tolower(x)	Lowercase


### paste

### sprintf

### nchar

### grep

### The sub and gsub functions

<hr>

Function	Description
substr(x, start=n1, stop=n2)	Extract or replace substrings in a character vector.
```{r}
x <- "abcdef" 
substr(x, 2, 4) # is "bcd" 
substr(x, 2, 4) <- "22222" # is "a222ef"
````
### The grep function
grep(pattern, x , ignore.case=FALSE, fixed=FALSE)	Search for pattern in x. If fixed =FALSE then pattern is a regular expression. If fixed=TRUE then pattern is a text string. Returns matching indices.
grep("A", c("b","A","c"), fixed=TRUE) returns 2
sub(pattern, replacement, x, ignore.case =FALSE, fixed=FALSE)	Find pattern in x and replace with replacement text. If fixed=FALSE then pattern is a regular expression.
If fixed = T then pattern is a text string. 
sub("\\s",".","Hello There") returns "Hello.There"
strsplit(x, split)	Split the elements of character vector x at split. 
strsplit("abc", "") returns 3 element vector "a","b","c"
paste(..., sep="")	Concatenate strings after using sep string to seperate them.
paste("x",1:3,sep="") returns c("x1","x2" "x3")
paste("x",1:3,sep="M") returns c("xM1","xM2" "xM3")
paste("Today is", date())
