

intent_morality
Moral judgments about third-party moral behavior.

#### Description

Moral judgments about third-party moral behavior.

#### Usage
<pre><code>

intent_morality

#### Format

A data frame with 4016 rows and 8 variables
A numeric variable.  id. Participant id.
item  gender. Participant’s gender.
item  item. Which story/vignette participants read for a given
condition
.
item  harm. What kind of harm was involved in the
item
.
item  belief. What kind of belief the actor had (neutral or negative/harmful).
item  outcome. What kind of outcome the actor caused (neutral or negative/harmful).
item  condition. Type of harm, composed of
belif
and
outcome
.
item  question. Type of moral judgment asked (
wrongess
or
punishment
).
item  rating. Moral judgment rating on a scale of 1 to 7.

#### Details
This dataset contains data from a recent study about how people judge behavior of others when they
unintentionally or intentionally cause harm to others.
Participants responded to four different vignettes that contains four different types of conditions-
*   accidental harm. neutral belief, harmful/negative outcome
item  intentional harm. harmful/negative belief, harmful/negative outcome
item  attempted harm. harmful/negative belief, neutral outcome
18
